import os

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView

from main_app.exec_ext_script import execute_ext_script
from main_app.forms import WebCrawlerForm
from main_app.models import WebCrawler

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    else:
        form = UserCreationForm()

    return render(request, 'registration/signup.html', {'form': form})


class WebCrawlerCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = WebCrawlerForm
        return render(request, 'main_app/web_crawler_form.html', {'form': form})

    def post(self, request):
        form = WebCrawlerForm(request.POST, request.FILES)

        if form.is_valid():
            web_crawler = form.save(commit=False)
            web_crawler.user = request.user
            web_crawler.save()
            return redirect('web_crawler_details', pk=web_crawler.id)
        else:
            return render(request, 'main_app/web_crawler_form.html', {'form': form})


class WebCrawlerDetails(LoginRequiredMixin, View):
    def get(self, request, pk):
        web_crawler = WebCrawler.objects.get(pk=pk)
        web_crawler_path = os.path.join(BASE_DIR, 'media', str(web_crawler.script))
        with open(web_crawler_path, 'r') as f:
            script_text = f.read()

        context = {
            'web_crawler': web_crawler,
            'script_text': script_text,
        }
        # Successful test of passing dict generated by external script to the context.
        context.update(execute_ext_script('media/main_app/user_1/weather_tvnmeteo.py'))

        return render(request, 'main_app/web_crawler_details.html', context)


class WebCrawlerList(LoginRequiredMixin, ListView):
    model = WebCrawler
    template_name = 'main_app/web_crawler_list.html'

    def get_queryset(self):
        return WebCrawler.objects.filter(user=self.request.user)
