# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebCrawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('web_crawler', models.FileField(upload_to=main_app.models.user_directory_path)),
            ],
        ),
    ]
